steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_IMAGE", "--build-arg", "GITHUB_TOKEN=$_GITHUB_TOKEN", "--build-arg", "GCLOUD_VERSION=$_GCLOUD_VERSION", "."]

images:
  - "$_IMAGE"
